/**
 * Rebuild `stars.data.js` from the Yale Bright Star Catalogue.
 *
 *   node celestial/extract-stars.js
 *
 * A developer tool, run deliberately, not something the page does. That
 * distinction is the whole reason the extract is committed: the atlas itself
 * makes no network call, and refreshing the data is an act somebody performs
 * and reviews in a diff.
 *
 * It fetches ~950 KB from a public MIT-licensed conversion of the catalogue,
 * which is public-domain data from Yale University Observatory. If that URL
 * ever dies, the committed extract keeps working — which is the second reason
 * for committing it.
 */

import { writeFile } from 'node:fs/promises';

const SOURCE_URL =
  'https://raw.githubusercontent.com/brettonw/YaleBrightStarCatalog/master/bsc5-short.json';

/**
 * The chosen subsets. Editing these lists and re-running is the supported way
 * to change what the sky layer holds — not editing `stars.data.js` by hand,
 * because a hand-typed coordinate is exactly the failure this layer names.
 */
const WANTED = {
  'bright-south': [
    'Sirius', 'Canopus', 'Rigil Kentaurus', 'Achernar', 'Hadar', 'Acrux',
    'Mimosa', 'Antares', 'Spica', 'Fomalhaut', 'Rigel', 'Betelgeuse',
    'Adhara', 'Aldebaran', 'Regulus', 'Altair', 'Procyon', 'Arcturus',
  ],
  pleiades: [
    'Alcyone', 'Atlas', 'Electra', 'Maia', 'Merope', 'Taygeta', 'Pleione',
    'Asterope', 'Sterope', 'Celaeno',
  ],
};

/**
 * The catalogue gives sexagesimal strings. These convert to the decimal hours
 * and degrees `star()` takes — and they throw rather than returning NaN,
 * because a silent NaN becomes a plausible-looking coordinate downstream.
 */
function raHours(text) {
  const m = /^(\d+)h\s*(\d+)m\s*([\d.]+)s$/.exec(text);
  if (!m) throw new Error(`unparseable right ascension: ${text}`);
  return Number(m[1]) + Number(m[2]) / 60 + Number(m[3]) / 3600;
}

function decDegrees(text) {
  const m = /^([+-])(\d+)°\s*(\d+)′\s*([\d.]+)″$/.exec(text);
  if (!m) throw new Error(`unparseable declination: ${text}`);
  const size = Number(m[2]) + Number(m[3]) / 60 + Number(m[4]) / 3600;
  return m[1] === '-' ? -size : size;
}

const response = await fetch(SOURCE_URL);
if (!response.ok) throw new Error(`${SOURCE_URL} → ${response.status}`);
const catalogue = await response.json();

// bsc5-short.json, not bsc5.json. The repository's README lists a `Common`
// field among the full file's computed fields; the full file does not carry
// one, and plain common names exist only in the short file's `N`. Checked
// against both rather than trusted.
//
// `N` is the common name and `C` is the constellation. They are one letter
// apart and confusing them yields a catalogue in which every star is named
// after its constellation — which is what happened on the first attempt.
const byName = new Map(catalogue.filter((s) => s.N).map((s) => [s.N, s]));

const lines = [];
for (const [group, names] of Object.entries(WANTED)) {
  for (const name of names) {
    const s = byName.get(name);
    if (!s) throw new Error(`"${name}" is not in the catalogue under that name`);
    const designation = [s.B, s.C].filter(Boolean).join(' ');
    lines.push(
      `  { id: 'HR${s.HR}', name: '${name}', designation: '${designation}', ` +
      `group: '${group}',\n    raHours: ${raHours(s.RA).toFixed(5)}, ` +
      `decDegrees: ${decDegrees(s.Dec) >= 0 ? '+' : ''}${decDegrees(s.Dec).toFixed(5)}, ` +
      `magnitude: ${Number(s.V)} },`);
  }
}

await writeFile(new URL('./stars.data.js', import.meta.url),
  '// GENERATED by extract-stars.js — do not hand-edit; re-run the script.\n' +
  'export const RAW = [\n' + lines.join('\n') + '\n];\n');

console.log(`wrote ${lines.length} stars from ${catalogue.length} in the catalogue`);
